const playlist = [

  "s--MDmshT3I&　北海道 函館山 函館市街",
  "DnrgCsF1nAM&　山形 蔵王体育館前",
  "owYeMn834xQ&　岩手 荒神神社",
  "z1MErdsqsw8&　福島 会津 湯野上温泉駅",
  "ZN4gh5IOowM&　東京 東京駅皇居側丸の内中央口",
  "nu6NE55_X7A&　東京 港区 東京タワー",
  "xEXHHrdZXME&　東京 台東 三ノ輪交差点",
  "HjRZNBm1kms&　東京 浅草 浅草寺",
  "Kozl3hd56Y0&　東京 江東区東雲 首都高速",
  "MwcMURMzJ7A&　東京 浅草 アサヒビール本社 スカイツリー",
  "66w-y4i91hE&　東京 築地",
  "xdjEmXaf8o8&　東京 勝どき",
  "_ByNEL0Ton4&　東京 台場 有明",
  "_k-5U7IeK8g&　東京 芝浦 レインボーブリッジ",
  "hlbh4P0Mz8M&　東京 お台場 レインボーブリッジ",
  "3KZ20aH_Oq4&　東京 江戸川区 荒川土手",
  "DjdUEyjx8GM&　東京 新宿歌舞伎町一番街A",
  "gFRtAAmiFbE&　東京 新宿歌舞伎町一番街B",
  "6dp-bvQ7RWo&　東京 新宿 大ガード",
  "dfVK7ld38Ys&　東京 渋谷 スクランブル交差点",
  "PSrW83NV0qo&　東京 豊島 スカイツリー",
  "fndY3LREfdE&　東京 世田谷 多摩川",
  "ZRUh9gNk8-g&　東京 あきる野市 秋川橋河川公園 バーベキューランド",
  "n1TtSZ7z7c0&　東京 小笠原 小港園地 八瀬川",
  "zKOa2NAlxXw&　東京 利島村 利島港",
  "pujEwBLh870&　神奈川 横浜 汽車道",
  "fl0YqYWGvd8&　神奈川 逗子マリーナ",
  "_ddxDN0eMnA&　神奈川 鎌倉 稲村ヶ崎 江ノ島 ",
  "PFqSE8GNfnE&　神奈川 鎌倉 七里ヶ浜 江ノ島 珊瑚礁から",
  "DgIbfgFdGVI&　神奈川 鎌倉 鎌倉高校前",
  "ESsZ9iB7tz0&　神奈川 鎌倉 腰越 漁港・海岸",
  "xPgeZzojY5o&　神奈川 藤沢 片瀬海岸 江ノ島 A",
  "ywXRfMLuw78&　神奈川 藤沢 片瀬海岸 江ノ島 B",
  "DoC_PlS1P_M&　神奈川 藤沢 江ノ島 ヨットハーバー",
  "qYnCG4J26d8&　神奈川 箱根 芦ノ湖",
  "GrEEoEmmrKs&　群馬 草津温泉 湯畑 A",
  "B_Sc1v1qR-g&　群馬 草津温泉 湯畑 B",
  "RT_yg_qsK_M&　群馬 草津温泉 西の河原",
  "P3bq6nGkpnE&　群馬 みなかみ町 雲越家住宅資料館",
  "Iv2VUE_UhRQ&　長野 上高地 河童橋",
  "F2NbYrc-gBU&　山梨 富士山 山中湖から",
  "JGyGoXlKZmw&　山梨 富士山 本栖湖リゾートから",
  "bdUbACCWmoY&　山梨 富士山 河口湖から",
  "1cnReFAU04k&　山梨 富士山 河口湖から",
  "PxzwnWh1dKk&　山梨 富士山 忍野八海から",
  "Xn7YQxxC5R0&　静岡 河津 河津川橋梁",
  "rB_nzP76ktc&　静岡 伊豆下田港",
  "6S4qvf97cbQ&　静岡 さった峠 東名高速道路 国道１号 JR東海道本線",
  "GsD9QQEKSzQ&　静岡 富士山 さった峠 東名高速 国道１号 JR東海道本線",
  "hBaHx5WdnbQ&　静岡 富士山 ふもとっぱら キャンプ場から",
  "pbmmZZJfBMw&　愛知 名古屋駅",
  "ZpzNv_hNxPE&　石川 金沢 兼六園",
  "jLZ_T91paAU&　福井 新保 国道８号",
  "lsxYH2XQQCg&　兵庫 淡路島モンキーパーク",
  "Pcj4xeEgbj8&　愛媛 瀬戸内 しまなみ海道／来島海峡大橋",
  "6g4Fh8K-MhY&　アメリカ ハワイ マウナケアの空",
  "iCxfe27HpaY&　スイス グリメンツ",
  "5uZa3-RMFos&　オーストラリア シドニー",
  "2tgHBRFHMm8&　オランダ アムステルダム セントラル",
  "89vRm9bb9_c&　フィンランド South Point Levi スキーリゾート",
  "ucfAqkh8c50&　フィンランド Adventure Park Levi",
  "AeMUdOPFcXI&　ナミビア エトシャ国立公園オカウクエジョの水場"
/* 最終行は末尾に,が入らないので注意！！ */


];
